services:
  redis:
      image: redis:7
      container_name: gadget_management_system_redis
      ports:
        - "6379:6379"
  db:
    image: postgres:15
    container_name: gadget_management_system_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: gadget_management_system_backend
    command: >
      sh -c "python manage.py migrate &&
            python manage.py load_initial_data &&
            daphne -b 0.0.0.0 -p 8000 gadget_management_system.asgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: gadget_management_system_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  postgres_data: